apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: smart-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-backend-image

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret

          ports:
            - containerPort: 5000

