apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-inventory
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Apurvbajpai2531/Smart-Inventory-Assistant.git
    targetRevision: main
    path: helm/smart-inventory

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
